version: '3.9'

services:
  frontend:
    image: example-frontend:latest
    build: .
    ports:
      - 5000:5000
    container_name: frontend
  backend:
    image: example-backend:latest
    build: .
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
    container_name: backend
  redis:
    image: redis:alpine3.17
    container_name: redis
