version: '3.9'

services:
  frontend:
    image: example-frontend:latest
    build: .
    ports:
      - 5000:5000
    container_name: frontend

  backend:
    image: example-backend:latest
    build: .
    ports:
      - 8080:8080
    container_name: backend
