version: '3.9'

services:
  frontend:
    image: example-frontend:latest
    build: .
    ports:
      - 5000:5000
    container_name: frontend
  backend:
    image: example-backend:latest
    build: .
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - redis
      - db
    container_name: backend
  db:
    image: postgres:alpine3.17
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./databases:/var/lib/postgresql/data
    container_name: postgres
  redis:
    image: redis:alpine3.17
    container_name: redis
